apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  labels:
    app: wordpress
  namespace: sag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

